name: Build UMDReplaceK Release Assets
on: release

jobs:

  build-release-win32:
    name: Build Windows x86 Releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build UMDReplaceK for normal Release
        run: |
          dotnet publish UMDReplaceK/UMDReplaceK.sln -c Release -r win-x86 --self-contained false -p:PublishSingleFile=true -p: -o win-x86
      - name: Build UMDReplaceK for portable Release
        run: |
          dotnet publish UMDReplaceK/UMDReplaceK.sln -c Release -r win-x86 --self-contained true -p:PublishSingleFile=true -o win-x86-sc
      - name: Rename executables
        run: |
          mv win-x86/UMDReplaceK.exe win-x86/UMDReplaceK-win32.exe
          mv win-x86-sc/UMDReplaceK.exe win-x86-sc/UMDReplaceK-Portable-win32.exe
      - name: Add normal build to release
        uses: djn24/add-asset-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: 'win-x86/UMDReplaceK-win32.exe'
      - name: Add portable build to release
        uses: djn24/add-asset-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: 'win-x86-sc/UMDReplaceK-Portable-win32.exe'

  build-release-win64:
    name: Build Windows x64 Releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build UMDReplaceK for normal Release
        run: |
          dotnet publish UMDReplaceK/UMDReplaceK.sln -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -p: -o win-x64
      - name: Build UMDReplaceK for portable Release
        run: |
          dotnet publish UMDReplaceK/UMDReplaceK.sln -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o win-x64-sc
      - name: Rename executables
        run: |
          mv win-x64/UMDReplaceK.exe win-x64/UMDReplaceK-win64.exe
          mv win-x64-sc/UMDReplaceK.exe win-x64-sc/UMDReplaceK-Portable-win64.exe
      - name: Add normal build to release
        uses: djn24/add-asset-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: 'win-x64/UMDReplaceK-win64.exe'
      - name: Add portable build to release
        uses: djn24/add-asset-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: 'win-x64-sc/UMDReplaceK-Portable-win64.exe'

  build-release-linux:
    name: Build Linux Releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build UMDReplaceK for normal Release
        run: |
          dotnet publish UMDReplaceK/UMDReplaceK.sln -c Release -r linux-x64 --self-contained false -p:PublishSingleFile=true -p: -o linux-x64
      - name: Build UMDReplaceK for portable Release
        run: |
          dotnet publish UMDReplaceK/UMDReplaceK.sln -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o linux-x64-sc
      - name: Rename executables
        run: |
          mv linux-x64/UMDReplaceK linux-x64/UMDReplaceK-linux
          mv linux-x64-sc/UMDReplaceK linux-x64-sc/UMDReplaceK-Portable-linux
      - name: Add normal build to release
        uses: djn24/add-asset-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: 'linux-x64/UMDReplaceK-linux'
      - name: Add portable build to release
        uses: djn24/add-asset-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: 'linux-x64-sc/UMDReplaceK-Portable-linux'

  build-release-osx:
    name: Build macOS Releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build UMDReplaceK for normal Release
        run: |
          dotnet publish UMDReplaceK/UMDReplaceK.sln -c Release -r osx-x64 --self-contained false -p:PublishSingleFile=true -p: -o osx-x64
      - name: Build UMDReplaceK for portable Release
        run: |
          dotnet publish UMDReplaceK/UMDReplaceK.sln -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -o osx-x64-sc
      - name: Rename executables
        run: |
          mv osx-x64/UMDReplaceK osx-x64/UMDReplaceK-osx
          mv osx-x64-sc/UMDReplaceK osx-x64-sc/UMDReplaceK-Portable-osx
      - name: Add normal build to release
        uses: djn24/add-asset-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: 'osx-x64/UMDReplaceK-osx'
      - name: Add portable build to release
        uses: djn24/add-asset-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: 'osx-x64-sc/UMDReplaceK-Portable-osx'